In [1]:
'''
numberical python
datatype of numpy is array

'''

'\nnumberical python\ndatatype of numpy is array\n\n'

In [2]:
import numpy as np

In [3]:
arr1 = np.array([1,3,5,7,9])

In [4]:
arr1

array([1, 3, 5, 7, 9])

In [5]:
type(arr1)

numpy.ndarray

In [6]:
arr1.shape                    #it will display the shape/dimension of an array

(5,)

In [7]:
arr1.sum()                    #it will give the sum of all elements in array

25

In [8]:
arr1.mean()                   #it will display the mean of all elements in array

5.0

In [9]:
arr1.std()                    #it will give the standard deviation of an array

2.8284271247461903

In [10]:
#creating 2d array
arr2 = np.array([[1,2,3,4,5]])

In [11]:
arr2

array([[1, 2, 3, 4, 5]])

In [12]:
arr2.shape    #display dimension of array  #(row,column)

(1, 5)

In [13]:
type(arr2)

numpy.ndarray

In [14]:
arr3 = np.array([
    [1,2,5],
[5,7,9]])

In [15]:
arr3

array([[1, 2, 5],
       [5, 7, 9]])

In [16]:
arr3.shape

(2, 3)

In [17]:
arr3[:]

array([[1, 2, 5],
       [5, 7, 9]])

In [18]:
arr3[:,2]

array([5, 9])

In [19]:
arr3[1,:]

array([5, 7, 9])

In [20]:
arr3[1:2]

array([[5, 7, 9]])

In [21]:
arr3[0,:]

array([1, 2, 5])

In [22]:
arr3[1,2] = 24

In [23]:
arr3

array([[ 1,  2,  5],
       [ 5,  7, 24]])

In [24]:
#axis= 0 represent row 
arr3.sum(axis=0)     #it will give the addition of elemnts  and represent in column

array([ 6,  9, 29])

In [25]:
#axis = 1 represent column
arr3.sum(axis=1)    #it will give the addition of elemnts  and represent in row

array([ 8, 36])

In [26]:
arr3.mean(axis=0)

array([ 3. ,  4.5, 14.5])

In [27]:
arr3.mean(axis=1)

array([ 2.66666667, 12.        ])

In [28]:
arr3.min(axis=0)

array([1, 2, 5])

In [29]:
arr3.mean(axis=1)

array([ 2.66666667, 12.        ])

In [30]:
arr3.max(axis=0)

array([ 5,  7, 24])

In [31]:
arr3.max(axis=1)

array([ 5, 24])

In [32]:
arr3.std(axis=0)

array([2. , 2.5, 9.5])

In [33]:
arr3.std(axis=1)

array([1.69967317, 8.52447457])

In [34]:
arr3.argmin()

0

In [35]:
arr3.max()

24

In [36]:
arr3.argmax(axis=0)

array([1, 1, 1], dtype=int64)

In [37]:
arr3.argmax(axis=1)

array([2, 2], dtype=int64)

In [38]:
arr3.argmin(axis=0)

array([0, 0, 0], dtype=int64)

In [39]:
arr3.argmin(axis=1)

array([0, 0], dtype=int64)

In [40]:
#creating random array
arr4 = np.random.rand(6,5)

In [41]:
arr4

array([[0.84675211, 0.52011486, 0.43438112, 0.02245929, 0.41824938],
       [0.45875788, 0.76694324, 0.27388786, 0.28808871, 0.43740783],
       [0.09109083, 0.57448689, 0.96737101, 0.52597249, 0.35798835],
       [0.86150742, 0.52464461, 0.18255402, 0.89379552, 0.06136226],
       [0.89623262, 0.16927928, 0.95202609, 0.53564089, 0.48400003],
       [0.23536626, 0.78960725, 0.02718134, 0.09828174, 0.12623546]])

In [42]:
arr4.reshape(6,-1)

array([[0.84675211, 0.52011486, 0.43438112, 0.02245929, 0.41824938],
       [0.45875788, 0.76694324, 0.27388786, 0.28808871, 0.43740783],
       [0.09109083, 0.57448689, 0.96737101, 0.52597249, 0.35798835],
       [0.86150742, 0.52464461, 0.18255402, 0.89379552, 0.06136226],
       [0.89623262, 0.16927928, 0.95202609, 0.53564089, 0.48400003],
       [0.23536626, 0.78960725, 0.02718134, 0.09828174, 0.12623546]])

In [43]:
#scalar operation on array

In [44]:
arr4*100

array([[84.67521058, 52.01148611, 43.43811244,  2.24592907, 41.8249383 ],
       [45.87578751, 76.694324  , 27.38878639, 28.80887119, 43.74078293],
       [ 9.10908315, 57.44868859, 96.73710056, 52.59724856, 35.79883476],
       [86.15074172, 52.46446061, 18.25540217, 89.37955177,  6.13622594],
       [89.62326169, 16.92792754, 95.20260928, 53.56408915, 48.40000348],
       [23.53662569, 78.96072527,  2.71813383,  9.8281744 , 12.62354587]])

In [45]:
arr4/100

array([[0.00846752, 0.00520115, 0.00434381, 0.00022459, 0.00418249],
       [0.00458758, 0.00766943, 0.00273888, 0.00288089, 0.00437408],
       [0.00091091, 0.00574487, 0.00967371, 0.00525972, 0.00357988],
       [0.00861507, 0.00524645, 0.00182554, 0.00893796, 0.00061362],
       [0.00896233, 0.00169279, 0.00952026, 0.00535641, 0.00484   ],
       [0.00235366, 0.00789607, 0.00027181, 0.00098282, 0.00126235]])

In [46]:
arr4 - arr4.max()

array([[-0.1206189 , -0.44725614, -0.53298988, -0.94491171, -0.54912162],
       [-0.50861313, -0.20042777, -0.69348314, -0.67928229, -0.52996318],
       [-0.87628017, -0.39288412,  0.        , -0.44139852, -0.60938266],
       [-0.10586359, -0.4427264 , -0.78481698, -0.07357549, -0.90600875],
       [-0.07113839, -0.79809173, -0.01534491, -0.43173011, -0.48337097],
       [-0.73200475, -0.17776375, -0.94018967, -0.86908926, -0.84113555]])

In [47]:
arr3

array([[ 1,  2,  5],
       [ 5,  7, 24]])

In [48]:
arr2

array([[1, 2, 3, 4, 5]])

In [49]:
arr5 = np.array([
    [1,3,5],
    [1,4,6],
])
arr5

array([[1, 3, 5],
       [1, 4, 6]])

In [50]:
arr3+arr5

array([[ 2,  5, 10],
       [ 6, 11, 30]])

In [51]:
arr3*arr5

array([[  1,   6,  25],
       [  5,  28, 144]])

In [52]:
np.matmul(arr3)

TypeError: matmul() takes from 2 to 3 positional arguments but 1 were given

In [ ]:
arr3-arr5

In [ ]:
arr3**3

In [ ]:
arr5/arr3.mean()

In [ ]:
arr5.mean()

# Trignometric functions

In [53]:
np.pi

3.141592653589793

In [54]:
np.sin(0)

0.0

In [55]:
np.sin(90)   # by default its taking 90 as radian

0.8939966636005579

In [56]:
np.sin(90*(np.pi/180))  

1.0

In [57]:
np.sin(np.deg2rad(60))

0.8660254037844386

In [58]:
np.tan(np.deg2rad(90))

1.633123935319537e+16

In [59]:
1/np.sin(np.deg2rad(50))

1.3054072893322786

In [60]:
1/np.cos(np.deg2rad(np.pi/4))

1.0000939590259186

In [61]:
1/np.cos(np.deg2rad(50))

1.5557238268604123

# Rounding operations

In [62]:
a= 1.256789
b=-2.45678

In [63]:
np.round(a)   # it will round the number

1.0

In [64]:
np.round(a,3) #it will round till specified decimal

1.257

In [65]:
np.abs(b)   # it will convert -ve to +ve

2.45678

In [66]:
np.ceil(a)  # it rounds to the next higher integer

2.0

In [67]:
np.ceil(b)

-2.0

In [68]:
np.trunc(a)    # it rounds to previous integer

1.0

In [69]:
np.trunc(b)

-2.0

In [70]:
np.sum?  # to get info of that function

SyntaxError: invalid syntax (<ipython-input-70-9376992cc1d2>, line 1)

In [71]:
help(np.sum)

Help on function sum in module numpy:

sum(a, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)
    Sum of array elements over a given axis.
    
    Parameters
    ----------
    a : array_like
        Elements to sum.
    axis : None or int or tuple of ints, optional
        Axis or axes along which a sum is performed.  The default,
        axis=None, will sum all of the elements of the input array.  If
        axis is negative it counts from the last to the first axis.
    
        .. versionadded:: 1.7.0
    
        If axis is a tuple of ints, a sum is performed on all of the axes
        specified in the tuple instead of a single axis or all the axes as
        before.
    dtype : dtype, optional
        The type of the returned array and of the accumulator in which the
        elements are summed.  The dtype of `a` is used by default unless `a`
        has an integer dtype of less precision than the default platform
        integer.  In 

# Matrix

In [72]:
m1 = np.matrix([[1,3,5],[2,4,6],[3,6,9]])
m2 = np.matrix([[2,3,4],[3,4,5],[9,8,7]])

In [73]:
m1

matrix([[1, 3, 5],
        [2, 4, 6],
        [3, 6, 9]])

In [74]:
m2

matrix([[2, 3, 4],
        [3, 4, 5],
        [9, 8, 7]])

In [75]:
type(m1)

numpy.matrix

In [76]:
m1+m2

matrix([[ 3,  6,  9],
        [ 5,  8, 11],
        [12, 14, 16]])

In [77]:
m1-m2

matrix([[-1,  0,  1],
        [-1,  0,  1],
        [-6, -2,  2]])

In [78]:
m1*2

matrix([[ 2,  6, 10],
        [ 4,  8, 12],
        [ 6, 12, 18]])

In [79]:
m1*m2*(m1+m2)

matrix([[1091, 1532, 1973],
        [1400, 1960, 2520],
        [2100, 2940, 3780]])

In [80]:
np.matmul(m1,m2)

matrix([[ 56,  55,  54],
        [ 70,  70,  70],
        [105, 105, 105]])

In [81]:
m4 = m1+m2
m4

matrix([[ 3,  6,  9],
        [ 5,  8, 11],
        [12, 14, 16]])

In [82]:
np.matmul(m1,m4)

matrix([[ 78, 100, 122],
        [ 98, 128, 158],
        [147, 192, 237]])

In [83]:
np.matmul(arr3,arr5)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [84]:
m3 = np.matrix([[1,2,3],[1,4,5]])
m3

matrix([[1, 2, 3],
        [1, 4, 5]])

In [85]:
m1.shape

(3, 3)

In [86]:
m1.T   #transpose of matrix

matrix([[1, 2, 3],
        [3, 4, 6],
        [5, 6, 9]])

In [87]:
m2.T

matrix([[2, 3, 9],
        [3, 4, 8],
        [4, 5, 7]])

In [88]:
np.linalg.det(m1)

0.0

In [89]:
np.linalg.det(m2)

0.0

In [90]:
np.linalg.inv(m2)

LinAlgError: Singular matrix

In [91]:
m5 = np.matrix([[1,2,0],[2,1,3],[1,0,1]])

In [92]:
m5

matrix([[1, 2, 0],
        [2, 1, 3],
        [1, 0, 1]])

In [93]:
np.linalg.det(m5)

2.9999999999999996

In [94]:
np.linalg.inv(m5)

matrix([[ 0.33333333, -0.66666667,  2.        ],
        [ 0.33333333,  0.33333333, -1.        ],
        [-0.33333333,  0.66666667, -1.        ]])

In [95]:
np.linalg.eigvals(m5)

array([ 3.52510225+0.j       , -0.26255113+0.8843676j,
       -0.26255113-0.8843676j])

In [96]:
m = np.matrix([[1,4],[3,2]])
m

matrix([[1, 4],
        [3, 2]])

In [97]:
np.linalg.eigvals(m)

array([-2.,  5.])

In [98]:
m = np.matrix([[2,0,0],[0,4,5],[0,4,3]])

In [99]:
m

matrix([[2, 0, 0],
        [0, 4, 5],
        [0, 4, 3]])

In [100]:
np.linalg.eigvals(m)

array([-1.,  8.,  2.])

In [101]:
np.linalg.eig(m)   #it will give eign values as well as eign vector

(array([-1.,  8.,  2.]),
 matrix([[ 0.        ,  0.        ,  1.        ],
         [ 0.70710678, -0.78086881,  0.        ],
         [-0.70710678, -0.62469505,  0.        ]]))

In [102]:
m7 = np.matrix(np.random.rand(3,3))
m7

matrix([[0.5324442 , 0.74943804, 0.70609922],
        [0.03221364, 0.12950095, 0.27207863],
        [0.92143914, 0.92130635, 0.57026919]])

In [103]:
np.linalg.eig(m7)

(array([ 1.54849865, -0.0388043 , -0.27748   ]),
 matrix([[-0.63970576, -0.49093113, -0.22359347],
         [-0.15872111,  0.76571247, -0.52940778],
         [-0.75205329, -0.41553704,  0.81837238]]))

In [104]:
m9 = np.matrix([[3,-1,1],[-1,3,1],[1,-1,3]])
m9

matrix([[ 3, -1,  1],
        [-1,  3,  1],
        [ 1, -1,  3]])

In [105]:
np.linalg.eig(m9)

(array([2., 4., 3.]),
 matrix([[ 7.07106781e-01, -7.07106781e-01,  5.77350269e-01],
         [ 7.07106781e-01,  2.40370336e-16,  5.77350269e-01],
         [ 1.12940492e-16, -7.07106781e-01,  5.77350269e-01]]))

In [106]:
mat = np.matrix([[1,1,1],[2,2,2],[3,3,3]])
mat

matrix([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

In [107]:
np.linalg.matrix_rank(mat)

1

In [108]:
mat1 = np.matrix([[1,2,3],[5,6,7],[8,9,10]])
mat1

matrix([[ 1,  2,  3],
        [ 5,  6,  7],
        [ 8,  9, 10]])

In [109]:
np.linalg.matrix_rank(mat1)

2

In [110]:
mat2 = np.matrix([[1,2,3],[2,4,6],[5,7,8]])
mat2


matrix([[1, 2, 3],
        [2, 4, 6],
        [5, 7, 8]])

In [111]:
np.linalg.matrix_rank(mat2)

2

In [112]:
np.ones((3,3))   # it will create array containing value as 1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [113]:
np.zeros((3,3))     # it will create array containing value as 0

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [114]:
arra1 = np.array([[1,2,3],[2,4,6],[3,6,9]])
arra1

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [115]:
np.linalg.det(arra1)

0.0

In [119]:
np.identity(3)   # it will create identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [120]:
np.random.choice([1,2,3,4,5])   # choose the random element from list

4

In [121]:
np.random.choice(["A","B","C","D"])    # choose the random element from list

'B'

In [122]:
np.array([[1,2,"A"],["A","B",1],[1,2,3]])

array([['1', '2', 'A'],
       ['A', 'B', '1'],
       ['1', '2', '3']], dtype='<U11')

In [123]:
np.matrix([[1,2,"A"],["A","B",1],[1,2,3]])

matrix([['1', '2', 'A'],
        ['A', 'B', '1'],
        ['1', '2', '3']], dtype='<U11')

# Solving system of linear equations

In [124]:
2x+3y=24
5x+2y=12

SyntaxError: invalid syntax (<ipython-input-124-73aff74e28d4>, line 1)

In [125]:
a = np.matrix([[2,3],[5,2]])
b = np.matrix([[24],[12]])

In [126]:
np.matmul(np.linalg.inv(a),b)

matrix([[-1.09090909],
        [ 8.72727273]])

In [127]:
2*-1.08 + 3*8.72

24.000000000000004

In [128]:
5*-1.08 + 2*8.72

12.040000000000001

In [129]:
'''
15x+30y+10z=100
x+y+z=30
2x+y+z=13
'''

'\n15x+30y+10z=100\nx+y+z=30\n2x+y+z=13\n'

In [130]:
a = np.matrix([[15,30,10],[1,1,1],[2,1,1]])
b = np.matrix([[100],[30],[13]])

In [131]:
np.matmul(np.linalg.inv(a),b)

matrix([[-17.  ],
        [ -5.75],
        [ 52.75]])

# Other important packages

In [132]:
from collections import Counter

In [133]:
arrx = [1,2,3,2,2,1,4,5,6,7,5]

In [134]:
Counter(arrx)   # it will count the distinct elements in array

Counter({1: 2, 2: 3, 3: 1, 4: 1, 5: 2, 6: 1, 7: 1})

In [135]:
freq_count = dict(Counter(arrx))  #converting to dict
freq_countl=list(Counter(arrx))
print(freq_count)
print(freq_countl)

{1: 2, 2: 3, 3: 1, 4: 1, 5: 2, 6: 1, 7: 1}
[1, 2, 3, 4, 5, 6, 7]


# permutation and combination

In [136]:
from itertools import combinations,permutations

In [137]:
arrs  = ["s","u","r","a","j"]

In [141]:
list(combinations(arrs,3))

[('s', 'u', 'r'),
 ('s', 'u', 'a'),
 ('s', 'u', 'j'),
 ('s', 'r', 'a'),
 ('s', 'r', 'j'),
 ('s', 'a', 'j'),
 ('u', 'r', 'a'),
 ('u', 'r', 'j'),
 ('u', 'a', 'j'),
 ('r', 'a', 'j')]

In [142]:
list(permutations(arrs,3))

[('s', 'u', 'r'),
 ('s', 'u', 'a'),
 ('s', 'u', 'j'),
 ('s', 'r', 'u'),
 ('s', 'r', 'a'),
 ('s', 'r', 'j'),
 ('s', 'a', 'u'),
 ('s', 'a', 'r'),
 ('s', 'a', 'j'),
 ('s', 'j', 'u'),
 ('s', 'j', 'r'),
 ('s', 'j', 'a'),
 ('u', 's', 'r'),
 ('u', 's', 'a'),
 ('u', 's', 'j'),
 ('u', 'r', 's'),
 ('u', 'r', 'a'),
 ('u', 'r', 'j'),
 ('u', 'a', 's'),
 ('u', 'a', 'r'),
 ('u', 'a', 'j'),
 ('u', 'j', 's'),
 ('u', 'j', 'r'),
 ('u', 'j', 'a'),
 ('r', 's', 'u'),
 ('r', 's', 'a'),
 ('r', 's', 'j'),
 ('r', 'u', 's'),
 ('r', 'u', 'a'),
 ('r', 'u', 'j'),
 ('r', 'a', 's'),
 ('r', 'a', 'u'),
 ('r', 'a', 'j'),
 ('r', 'j', 's'),
 ('r', 'j', 'u'),
 ('r', 'j', 'a'),
 ('a', 's', 'u'),
 ('a', 's', 'r'),
 ('a', 's', 'j'),
 ('a', 'u', 's'),
 ('a', 'u', 'r'),
 ('a', 'u', 'j'),
 ('a', 'r', 's'),
 ('a', 'r', 'u'),
 ('a', 'r', 'j'),
 ('a', 'j', 's'),
 ('a', 'j', 'u'),
 ('a', 'j', 'r'),
 ('j', 's', 'u'),
 ('j', 's', 'r'),
 ('j', 's', 'a'),
 ('j', 'u', 's'),
 ('j', 'u', 'r'),
 ('j', 'u', 'a'),
 ('j', 'r', 's'),
 ('j', 'r'

In [143]:
# enumerate function

In [144]:
for i,j in enumerate(arrs):     # runs two loops at a time
    print(i,j)

0 s
1 u
2 r
3 a
4 j


In [145]:
a = [1,2,3]
b = ['a','b','c']
c = [1.0,2.0,3.0]
d = ['q','r','s']

In [149]:
for i,(b,d) in enumerate(b,d):
    print(i,(b,d))

TypeError: 'list' object cannot be interpreted as an integer

In [150]:
for i,j,k in zip(a,b,c):
    print(i,j,k)

1 a 1.0
2 b 2.0
3 c 3.0


In [151]:
# lambda function : temporary functions, once executed removed from memory

In [152]:
list(map(lambda x: x**2,np.array([1,2,3,4])))

[1, 4, 9, 16]

In [153]:
list(map(lambda x: x < 2,np.array([1,2,3,4])))

[True, False, False, False]

In [154]:
# filter
list(filter(lambda x: x > 2,np.array([1,2,3,4])))

[3, 4]

In [155]:
## Date time

In [156]:
import datetime as dt 

In [157]:
dt.datetime.now()  #shows current time

datetime.datetime(2022, 10, 31, 13, 59, 46, 396050)

In [158]:
dt.date.today()     # shows todays date

datetime.date(2022, 10, 31)

In [159]:
date_string = '2022-01-01'
dt.datetime.strptime(date_string,"%Y-%m-%d")

datetime.datetime(2022, 1, 1, 0, 0)